export const nav = [
  {
    id: "start",
    title: "开始使用",
    category: "guide",
    group: "开始使用",
    keywords: "getting started 安装 使用",
  },
  {
    id: "overview",
    title: "项目介绍",
    category: "guide",
    group: "开始使用",
    keywords: "overview introduction Octane Ant Design Antdv Next 开源 来源",
  },
  {
    id: "for-agents",
    title: "面向 AI Agent",
    category: "guide",
    group: "AI",
    keywords: "AI Agent llms CLI MCP 安装 代码生成",
  },
  {
    id: "theme",
    title: "定制主题",
    category: "guide",
    group: "进阶使用",
    keywords: "theme token ConfigProvider Tailwind StyleX 暗色",
  },
  {
    id: "tailwindcss",
    title: "Tailwind CSS",
    category: "guide",
    group: "进阶使用",
    keywords: "tailwind layers 样式 工具类",
  },
  {
    id: "api-conventions",
    title: "API 与语法约定",
    category: "guide",
    group: "进阶使用",
    keywords: "ref current useState onChange 受控 事件",
  },
  {
    id: "compatibility",
    title: "兼容与迁移",
    category: "guide",
    group: "迁移",
    keywords: "limitations differences migration 支持范围",
  },
  {
    id: "contributing",
    title: "参与贡献",
    category: "guide",
    group: "其他",
    keywords: "contribute develop docs check build PR 贡献 开发",
  },
  {
    id: "changelog",
    title: "更新日志",
    category: "guide",
    group: "其他",
    keywords: "changelog release alpha version npm 版本 更新",
  },
  {
    id: "components",
    title: "组件总览",
    category: "components",
    group: "组件",
    keywords: "components",
  },
  {
    id: "button",
    title: "Button 按钮",
    category: "components",
    group: "通用",
    keywords: "button 按钮",
  },
  {
    id: "typography",
    title: "Typography 排版",
    category: "components",
    group: "通用",
    keywords: "typography 标题 文本 复制 编辑",
  },
  {
    id: "flex",
    title: "Flex 弹性布局",
    category: "components",
    group: "布局",
    keywords: "flex 弹性布局",
  },
  {
    id: "space",
    title: "Space 间距",
    category: "components",
    group: "布局",
    keywords: "space 间距",
  },
  {
    id: "divider",
    title: "Divider 分割线",
    category: "components",
    group: "布局",
    keywords: "divider 分割线",
  },
  {
    id: "switch",
    title: "Switch 开关",
    category: "components",
    group: "数据录入",
    keywords: "switch 开关",
  },
  {
    id: "auto-complete",
    title: "AutoComplete 自动完成",
    category: "components",
    group: "数据录入",
    keywords: "autocomplete 自动完成 输入建议 搜索",
  },
  {
    id: "form",
    title: "Form 表单",
    category: "components",
    group: "数据录入",
    keywords: "form 表单 校验 提交 重置",
  },
  {
    id: "input",
    title: "Input 输入框",
    category: "components",
    group: "数据录入",
    keywords: "input text 输入 表单",
  },
  {
    id: "input-number",
    title: "InputNumber 数字输入框",
    category: "components",
    group: "数据录入",
    keywords: "number 数字输入框 步进",
  },
  {
    id: "select",
    title: "Select 选择器",
    category: "components",
    group: "数据录入",
    keywords: "select 选择器 单选 搜索 选项",
  },
  {
    id: "slider",
    title: "Slider 滑动输入条",
    category: "components",
    group: "数据录入",
    keywords: "slider 滑动输入条 范围",
  },
  {
    id: "checkbox",
    title: "Checkbox 多选框",
    category: "components",
    group: "数据录入",
    keywords: "checkbox check 多选 表单",
  },
  {
    id: "radio",
    title: "Radio 单选框",
    category: "components",
    group: "数据录入",
    keywords: "radio 单选框",
  },
  {
    id: "tag",
    title: "Tag 标签",
    category: "components",
    group: "数据展示",
    keywords: "tag 标签",
  },
  {
    id: "spin",
    title: "Spin 加载中",
    category: "components",
    group: "反馈",
    keywords: "spin Spin 加载中",
  },
  {
    id: "skeleton",
    title: "Skeleton 骨架屏",
    category: "components",
    group: "反馈",
    keywords: "skeleton Skeleton 骨架屏",
  },
  {
    id: "progress",
    title: "Progress 进度条",
    category: "components",
    group: "反馈",
    keywords: "progress Progress 进度条",
  },
  {
    id: "result",
    title: "Result 结果",
    category: "components",
    group: "反馈",
    keywords: "result Result 结果",
  },
  {
    id: "alert",
    title: "Alert 警告提示",
    category: "components",
    group: "反馈",
    keywords: "alert 警告提示",
  },
  {
    id: "list",
    title: "List 列表",
    category: "components",
    group: "数据展示",
    keywords: "list 列表 网格",
  },
  {
    id: "card",
    title: "Card 卡片",
    category: "components",
    group: "数据展示",
    keywords: "card 卡片",
  },
  {
    id: "badge",
    title: "Badge 徽标数",
    category: "components",
    group: "数据展示",
    keywords: "badge 徽标数",
  },
  {
    id: "avatar",
    title: "Avatar 头像",
    category: "components",
    group: "数据展示",
    keywords: "avatar 头像",
  },
  {
    id: "grid",
    title: "Grid 栅格",
    category: "components",
    group: "布局",
    keywords: "grid 栅格",
  },
  {
    id: "layout",
    title: "Layout 布局",
    category: "components",
    group: "布局",
    keywords: "layout 布局",
  },
  {
    id: "collapse",
    title: "Collapse 折叠面板",
    category: "components",
    group: "数据展示",
    keywords: "collapse 折叠面板",
  },
  {
    id: "segmented",
    title: "Segmented 分段控制器",
    category: "components",
    group: "数据展示",
    keywords: "Segmented 分段控制器",
  },
  {
    id: "rate",
    title: "Rate 评分",
    category: "components",
    group: "数据录入",
    keywords: "Rate 评分",
  },
  {
    id: "breadcrumb",
    title: "Breadcrumb 面包屑",
    category: "components",
    group: "导航",
    keywords: "Breadcrumb 面包屑",
  },
  {
    id: "pagination",
    title: "Pagination 分页",
    category: "components",
    group: "导航",
    keywords: "Pagination 分页",
  },
  {
    id: "steps",
    title: "Steps 步骤条",
    category: "components",
    group: "导航",
    keywords: "Steps 步骤条",
  },
  {
    id: "tooltip",
    title: "Tooltip 文字提示",
    category: "components",
    group: "数据展示",
    keywords: "Tooltip 文字提示",
  },
  {
    id: "popover",
    title: "Popover 气泡卡片",
    category: "components",
    group: "数据展示",
    keywords: "Popover 气泡卡片",
  },
  {
    id: "tabs",
    title: "Tabs 标签页",
    category: "components",
    group: "数据展示",
    keywords: "tabs 标签页",
  },
  {
    id: "empty",
    title: "Empty 空状态",
    category: "components",
    group: "数据展示",
    keywords: "empty 空状态",
  },
  {
    id: "statistic",
    title: "Statistic 统计数值",
    category: "components",
    group: "数据展示",
    keywords: "statistic 统计数值",
  },
  {
    id: "timeline",
    title: "Timeline 时间轴",
    category: "components",
    group: "数据展示",
    keywords: "timeline 时间轴",
  },
  {
    id: "descriptions",
    title: "Descriptions 描述列表",
    category: "components",
    group: "数据展示",
    keywords: "descriptions 描述列表",
  },
  {
    id: "message",
    title: "Message 全局提示",
    category: "components",
    group: "反馈",
    keywords: "Message 全局提示",
  },
  {
    id: "notification",
    title: "Notification 通知提醒框",
    category: "components",
    group: "反馈",
    keywords: "Notification 通知提醒框",
  },
  {
    id: "modal",
    title: "Modal 对话框",
    category: "components",
    group: "反馈",
    keywords: "Modal 对话框",
  },
  {
    id: "drawer",
    title: "Drawer 抽屉",
    category: "components",
    group: "反馈",
    keywords: "Drawer 抽屉",
  },
  {
    id: "menu",
    title: "Menu 导航菜单",
    category: "components",
    group: "导航",
    keywords: "Menu 导航菜单",
  },
  {
    id: "dropdown",
    title: "Dropdown 下拉菜单",
    category: "components",
    group: "导航",
    keywords: "Dropdown 下拉菜单",
  },
  {
    id: "popconfirm",
    title: "Popconfirm 气泡确认框",
    category: "components",
    group: "反馈",
    keywords: "Popconfirm 气泡确认框",
  },
  {
    id: "affix",
    title: "Affix 固钉",
    category: "components",
    group: "其他",
    keywords: "Affix 固钉",
  },
  {
    id: "anchor",
    title: "Anchor 锚点",
    category: "components",
    group: "导航",
    keywords: "Anchor 锚点",
  },
  {
    id: "float-button",
    title: "FloatButton 悬浮按钮",
    category: "components",
    group: "通用",
    keywords: "FloatButton 悬浮按钮",
  },
  {
    id: "image",
    title: "Image 图片",
    category: "components",
    group: "数据展示",
    keywords: "Image 图片",
  },
  {
    id: "carousel",
    title: "Carousel 走马灯",
    category: "components",
    group: "数据展示",
    keywords: "Carousel 走马灯",
  },
  {
    id: "splitter",
    title: "Splitter 分隔面板",
    category: "components",
    group: "布局",
    keywords: "Splitter 分隔面板",
  },
  {
    id: "watermark",
    title: "Watermark 水印",
    category: "components",
    group: "反馈",
    keywords: "Watermark 水印",
  },
  {
    id: "app",
    title: "App 包裹组件",
    category: "components",
    group: "其他",
    keywords: "App 包裹组件",
  },
  {
    id: "icon",
    title: "Icon 图标",
    category: "components",
    group: "通用",
    keywords: "Icon 图标",
  },
  {
    id: "tour",
    title: "Tour 漫游式引导",
    category: "components",
    group: "数据展示",
    keywords: "Tour 漫游式引导",
  },
  {
    id: "qr-code",
    title: "QRCode 二维码",
    category: "components",
    group: "数据展示",
    keywords: "QRCode 二维码",
  },
];
export const toc: Record<string, [string, string][]> = {
  overview: [
    ["features", "特性"],
    ["environment", "支持环境"],
    ["progress", "当前进度"],
    ["contribute", "参与贡献"],
    ["upstream", "上游项目与致谢"],
  ],
  start: [
    ["integration", "安装组件库"],
    ["configure", "配置 Vite 与 TypeScript"],
    ["usage", "使用组件"],
    ["run", "运行与检查"],
    ["troubleshooting", "遇到问题"],
  ],
  contributing: [
    ["install", "开发本库与文档站"],
    ["build", "仓库构建与验证"],
  ],
  changelog: [
    ["alpha-6", "0.1.0-alpha.6"],
    ["alpha-5", "0.1.0-alpha.5"],
    ["alpha-4", "0.1.0-alpha.4"],
    ["alpha-3", "0.1.0-alpha.3"],
    ["alpha-2", "0.1.0-alpha.2"],
    ["alpha-1", "0.1.0-alpha.1"],
    ["alpha-0", "0.1.0-alpha.0"],
  ],
  theme: [
    ["configure", "配置主题"],
    ["brand", "修改主题变量"],
    ["algorithms", "使用预设算法"],
    ["component-token", "修改组件变量"],
    ["nested", "局部主题与动态切换"],
    ["styling", "Tailwind CSS 与 StyleX"],
    ["limitations", "迁移边界"],
  ],
  components: [
    ["general", "通用"],
    ["layout", "布局"],
    ["navigation", "导航"],
    ["entry", "数据录入"],
    ["display", "数据展示"],
    ["feedback", "反馈"],
    ["other", "其他"],
    ["coverage", "完整覆盖清单"],
    ["configuration", "主题与配置"],
  ],
  "api-conventions": [
    ["state", "状态与受控输入"],
    ["refs", "ref 与原生事件"],
    ["planned", "后续 API 的边界"],
  ],
  compatibility: [
    ["matrix", "支持矩阵"],
    ["migration", "迁移检查"],
    ["migration-example", "表单迁移示例"],
    ["pending", "待验证能力"],
  ],
  input: [
    ["when", "何时使用"],
    ["examples", "代码演示"],
    ["basic", "基本使用"],
    ["sizes", "三种大小"],
    ["controlled", "受控输入"],
    ["states", "状态"],
    ["refs", "聚焦与选择"],
    ["affix", "前后缀与清除"],
    ["password", "密码输入"],
    ["password-controlled", "受控密码可见性"],
    ["search", "搜索框"],
    ["textarea", "自动高度文本域"],
    ["native-length", "原生长度限制"],
    ["show-count", "内置字数统计"],
    ["api", "API"],
    ["tokens", "主题变量"],
    ["limitations", "已知差异"],
  ],
  checkbox: [
    ["group", "多选组合"],
    ["when", "何时使用"],
    ["examples", "代码演示"],
    ["basic", "基本使用"],
    ["states", "不可用"],
    ["controlled", "受控选择"],
    ["all", "全选与中间态"],
    ["group-layout", "自定义组布局"],
    ["api", "API"],
    ["tokens", "主题变量"],
    ["limitations", "已知差异"],
  ],
  button: [
    ["when", "何时使用"],
    ["examples", "代码演示"],
    ["basic", "按钮类型"],
    ["sizes", "尺寸与形状"],
    ["states", "状态与反馈"],
    ["icon-placement", "图标位置"],
    ["delayed-loading", "延迟与自定义加载"],
    ["ghost-actions", "幽灵、危险与块级"],
    ["native-form-link", "原生提交与链接"],
    ["nested", "嵌套主题"],
    ["component", "组件级覆盖"],
    ["api", "API"],
    ["refs", "事件与 ref"],
    ["tokens", "主题变量"],
    ["limitations", "已知差异"],
    ["faq", "常见问题"],
  ],
};

toc.flex = [
  ["examples", "代码演示"],
  ["basic", "基本使用"],
  ["alignment", "主轴对齐"],
  ["wrapping", "换行与伸缩"],
  ["cross-axis", "交叉轴对齐"],
  ["gap", "设置间隙"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.space = [
  ["examples", "代码演示"],
  ["basic", "基本使用"],
  ["sizes", "间距尺寸"],
  ["layout", "自动换行"],
  ["vertical", "垂直间距"],
  ["alignment", "对齐"],
  ["split", "分隔符"],
  ["compact", "紧凑组合"],
  ["compact-size", "紧凑尺寸"],
  ["compact-vertical", "垂直紧凑布局"],
  ["compact-addon", "前后缀与禁用"],
  ["api", "API"],
  ["compact-api", "Space.Compact / Space.Addon"],
  ["tokens", "主题与支持范围"],
];
toc.divider = [
  ["examples", "代码演示"],
  ["basic", "水平分割线"],
  ["orientation", "标题位置与样式"],
  ["plain", "正文样式"],
  ["vertical", "垂直分割线"],
  ["dashed", "虚线"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.switch = [
  ["examples", "代码演示"],
  ["basic", "基本使用与状态"],
  ["controlled", "受控状态"],
  ["save-flow", "等待保存结果"],
  ["form-binding", "表单绑定"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.radio = [
  ["when", "何时使用"],
  ["examples", "代码演示"],
  ["basic", "基本使用"],
  ["more", "组合与交互"],
  ["vertical", "纵向排列与更多选项"],
  ["button-sizes", "按钮尺寸与整行布局"],
  ["disabled", "组禁用与单项禁用"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.tag = [
  ["when", "何时使用"],
  ["examples", "代码演示"],
  ["basic", "基本使用"],
  ["more", "组合与交互"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.alert = [
  ["when", "何时使用"],
  ["examples", "代码演示"],
  ["basic", "基本使用"],
  ["more", "组合与交互"],
  ["retry", "错误恢复与关闭回调"],
  ["announcements", "切换顶部公告"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.card = [
  ["when", "何时使用"],
  ["examples", "代码演示"],
  ["basic", "基本使用"],
  ["more", "组合与交互"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.badge = [
  ["when", "何时使用"],
  ["examples", "代码演示"],
  ["basic", "基本使用"],
  ["more", "组合与交互"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.avatar = [
  ["when", "何时使用"],
  ["examples", "代码演示"],
  ["basic", "基本使用"],
  ["more", "组合与交互"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.grid = [
  ["examples", "代码演示"],
  ["basic", "基础栅格"],
  ["more", "响应式布局"],
  ["gutter", "区块间隔"],
  ["offset", "左右偏移"],
  ["order", "排序"],
  ["alignment", "对齐"],
  ["flex-fill", "Flex 填充"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.layout = [
  ["examples", "代码演示"],
  ["basic", "上下结构"],
  ["more", "响应式侧栏"],
  ["header-sider", "顶部与侧边布局"],
  ["custom-trigger", "自定义触发器"],
  ["sticky-header", "固定头部"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.collapse = [
  ["examples", "代码演示"],
  ["basic", "折叠与状态保留"],
  ["more", "手风琴与独立操作"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.tabs = [
  ["examples", "代码演示"],
  ["basic", "切换与键盘操作"],
  ["more", "新增和关闭标签"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.empty = [
  ["examples", "代码演示"],
  ["basic", "空状态"],
  ["more", "简洁图与操作入口"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.statistic = [
  ["examples", "代码演示"],
  ["basic", "数值与金额"],
  ["more", "字符串精度"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.timeline = [
  ["examples", "代码演示"],
  ["basic", "事件与状态"],
  ["more", "交替布局与等待状态"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.descriptions = [
  ["examples", "代码演示"],
  ["basic", "成组信息"],
  ["more", "响应式与边框"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.typography = [
  ["examples", "代码演示"],
  ["basic", "文字层级与修饰"],
  ["headings", "标题层级"],
  ["text", "文本与超链接"],
  ["editable", "可编辑"],
  ["controlled-edit", "受控编辑"],
  ["copyable", "可复制"],
  ["ellipsis", "省略号"],
  ["expand", "受控展开与收起"],
  ["suffix", "保留后缀"],
  ["api", "API"],
  ["configuration", "交互配置"],
  ["tokens", "主题与支持范围"],
];
toc.list = [
  ["examples", "代码演示"],
  ["basic", "带操作的列表"],
  ["more", "响应式网格与空状态"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.spin = [
  ["examples", "代码演示"],
  ["basic", "三种尺寸"],
  ["more", "局部加载与延迟"],
  ["fullscreen", "全屏刷新反馈"],
  ["indicator", "自定义指示器"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.skeleton = [
  ["examples", "代码演示"],
  ["basic", "内容占位"],
  ["more", "独立占位组件"],
  ["layout", "按内容结构配置"],
  ["element-sizes", "独立占位尺寸"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.progress = [
  ["examples", "代码演示"],
  ["basic", "进度与状态"],
  ["more", "圆形、仪表盘与步骤"],
  ["verification", "传输完成后的校验进度"],
  ["gradient", "渐变颜色"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.result = [
  ["examples", "代码演示"],
  ["basic", "成功与后续操作"],
  ["more", "异常页面"],
  ["error-details", "错误详情与重新检查"],
  ["custom-icon", "警告结果与自定义图标"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.segmented = [
  ["examples", "代码演示"],
  ["basic", "基本用法与尺寸"],
  ["more", "受控值与布局"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.select = [
  ["examples", "代码演示"],
  ["basic", "基本用法"],
  ["controlled", "搜索与受控值"],
  ["filter-empty", "自定义过滤与空结果"],
  ["multiple", "多选与搜索"],
  ["controlled-multiple", "受控多选与移除回调"],
  ["controlled-open", "受控展开与选中回调"],
  ["sizes-status", "尺寸与校验状态"],
  ["coordinated", "省市联动"],
  ["api", "API"],
  ["types", "选项与回调类型"],
  ["scope", "支持范围"],
];

toc["auto-complete"] = [
  ["when", "何时使用"],
  ["examples", "代码演示"],
  ["basic", "自由输入"],
  ["dynamic", "动态邮箱建议"],
  ["controlled", "受控值与事件"],
  ["filter", "内置与自定义过滤"],
  ["clear", "清除与回调"],
  ["states", "尺寸、状态与禁用"],
  ["empty-open", "空列表与受控展开"],
  ["ref-container", "聚焦与局部浮层"],
  ["api", "API"],
  ["scope", "支持范围"],
];

toc.form = [
  ["when", "何时使用"],
  ["examples", "代码演示"],
  ["basic", "填写并提交"],
  ["instance", "实例方法"],
  ["validation", "手动校验与重置"],
  ["layout", "表单布局"],
  ["async-validation", "异步用户名校验"],
  ["array-mapping", "绑定数组属性"],
  ["custom-trigger", "自定义事件与多参数"],
  ["value-props", "存储值与显示值"],
  ["api", "API"],
  ["instance-api", "FormInstance 方法"],
  ["scope", "支持范围"],
];

toc.rate = [
  ["examples", "代码演示"],
  ["basic", "基本、半星与只读"],
  ["more", "受控评分与自定义字符"],
  ["hover-text", "悬停说明"],
  ["clear", "是否允许点击清零"],
  ["characters", "自定义字符与数量"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.breadcrumb = [
  ["examples", "代码演示"],
  ["basic", "层级导航"],
  ["more", "自定义分隔符"],
  ["path-navigation", "路径下钻"],
  ["icons", "带有图标"],
  ["separator-items", "独立分隔符"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.pagination = [
  ["examples", "代码演示"],
  ["uncontrolled", "基本"],
  ["basic", "受控分页"],
  ["more", "迷你"],
  ["filtered-total", "筛选后重置页码"],
  ["size-change", "改变每页条数"],
  ["quick-jump", "跳转"],
  ["simple", "简洁"],
  ["total", "总数"],
  ["item-render", "上一页与下一页"],
  ["disabled", "禁用"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.steps = [
  ["examples", "代码演示"],
  ["basic", "顺序流程"],
  ["more", "可点击的纵向步骤"],
  ["validation-gate", "校验与错误状态"],
  ["mini", "迷你版"],
  ["icons", "带图标的步骤条"],
  ["item-status", "步骤运行错误"],
  ["label-placement", "标签放置位置"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.tooltip = [
  ["examples", "代码演示"],
  ["basic", "基本提示"],
  ["more", "十二种位置"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.popover = [
  ["examples", "代码演示"],
  ["basic", "多种触发方式"],
  ["more", "受控显示与操作"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc["input-number"] = [
  ["examples", "代码演示"],
  ["basic", "尺寸与状态"],
  ["more", "精度、格式化与受控值"],
  ["boundaries", "动态边界与受控值"],
  ["controls", "步进按钮与键盘"],
  ["step", "小数步长与步进回调"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.slider = [
  ["examples", "代码演示"],
  ["basic", "受控单值"],
  ["more", "范围、刻度与方向"],
  ["input-number", "与数字输入同步"],
  ["complete", "操作完成回调"],
  ["tooltip", "提示格式与独立刻度"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.message = [
  ["examples", "代码演示"],
  ["basic", "提示类型与自动关闭"],
  ["more", "主题继承与消息更新"],
  ["lifecycle", "请求过程与手动关闭"],
  ["close-promise", "等待提示关闭"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.notification = [
  ["examples", "代码演示"],
  ["basic", "类型、位置与自动关闭"],
  ["more", "更新内容与操作按钮"],
  ["persistent", "持续通知与关闭回调"],
  ["app-context", "通过 App 使用共享实例"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.modal = [
  ["examples", "代码演示"],
  ["basic", "受控打开与确认反馈"],
  ["more", "嵌套浮层与内容保留"],
  ["footer", "自定义操作区"],
  ["button-props", "确认按钮条件"],
  ["lifecycle", "关闭时保留或销毁"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.drawer = [
  ["examples", "代码演示"],
  ["basic", "四个方向"],
  ["more", "关闭后销毁内容"],
  ["sizes", "预设尺寸与遮罩行为"],
  ["nested", "多层抽屉"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.menu = [
  ["examples", "代码演示"],
  ["basic", "内嵌导航"],
  ["more", "水平菜单"],
  ["controlled-tree", "受控展开与多选"],
  ["single-open", "只展开当前父级"],
  ["mode", "切换菜单类型"],
  ["item-types", "菜单项与分组"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.dropdown = [
  ["examples", "代码演示"],
  ["basic", "点击展开"],
  ["more", "悬停触发"],
  ["controlled-open", "受控展开"],
  ["placement", "弹出位置"],
  ["selection", "菜单选择"],
  ["context", "右键菜单"],
  ["disabled", "禁用"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.popconfirm = [
  ["examples", "代码演示"],
  ["basic", "确认与取消"],
  ["more", "异步确认"],
  ["controlled", "受控显示与自定义文案"],
  ["retry", "失败后保留确认框"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.affix = [
  ["examples", "代码演示"],
  ["basic", "指定滚动容器"],
  ["more", "固定到底部"],
  ["offset", "动态偏移与状态回调"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.anchor = [
  ["examples", "代码演示"],
  ["basic", "容器内定位"],
  ["more", "横向导航"],
  ["nested", "嵌套与链接改变"],
  ["custom-click", "自定义点击"],
  ["custom-active", "自定义高亮"],
  ["offset", "滚动偏移"],
  ["history", "替换历史记录"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc["float-button"] = [
  ["examples", "代码演示"],
  ["basic", "基础操作"],
  ["more", "按钮组与返回顶部"],
  ["controlled", "受控浮动菜单"],
  ["static-group", "常驻按钮组与链接"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.image = [
  ["examples", "代码演示"],
  ["basic", "基本用法"],
  ["more", "交互与状态"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.carousel = [
  ["examples", "代码演示"],
  ["basic", "基本用法"],
  ["more", "交互与状态"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.splitter = [
  ["examples", "代码演示"],
  ["basic", "基础拖拽与尺寸约束"],
  ["more", "垂直方向"],
  ["controlled", "受控模式"],
  ["multiple", "多面板"],
  ["nested", "复杂组合"],
  ["resizable", "禁用调整"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.watermark = [
  ["examples", "代码演示"],
  ["basic", "多行文字水印"],
  ["more", "图片、间距与旋转"],
  ["config", "水印参数预览"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.app = [
  ["examples", "代码演示"],
  ["basic", "共享实例"],
  ["more", "不增加容器"],
  ["config", "消息与通知默认配置"],
  ["nested", "嵌套 App 的实例隔离"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];
toc.icon = [
  ["examples", "代码演示"],
  ["basic", "基本用法"],
  ["more", "交互与状态"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc["qr-code"] = [
  ["examples", "代码演示"],
  ["basic", "内容与渲染方式"],
  ["more", "状态与颜色"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.tour = [
  ["examples", "代码演示"],
  ["basic", "基本用法"],
  ["api", "API"],
  ["tokens", "主题与支持范围"],
];

toc.tailwindcss = [
  ["setup", "安装与编译"],
  ["layers", "样式层级"],
  ["usage", "布局工具类"],
  ["tokens", "主题映射"],
  ["agents", "Agent 接入约束"],
  ["references", "参考与范围"],
];

toc["for-agents"] = [
  ["baseline", "先确认基线"],
  ["context", "Agent 上下文"],
  ["usage", "状态与反馈"],
  ["boundaries", "API 边界"],
];
