export const nav = [
  {
    id: "overview",
    title: "项目介绍",
    category: "guide",
    group: "开始",
    keywords: "overview introduction",
  },
  {
    id: "start",
    title: "快速开始",
    category: "guide",
    group: "开始",
    keywords: "getting started 安装 使用",
  },
  {
    id: "theme",
    title: "定制主题",
    category: "guide",
    group: "进阶使用",
    keywords: "theme token ConfigProvider Tailwind StyleX 暗色",
  },
  {
    id: "api-conventions",
    title: "API 与语法约定",
    category: "guide",
    group: "进阶使用",
    keywords: "ref current useState onChange 受控 事件",
  },
  {
    id: "compatibility",
    title: "兼容与迁移",
    category: "guide",
    group: "其他",
    keywords: "limitations differences migration 支持范围",
  },
  {
    id: "components",
    title: "组件总览",
    category: "components",
    group: "组件",
    keywords: "components",
  },
  {
    id: "button",
    title: "Button 按钮",
    category: "components",
    group: "通用",
    keywords: "button 按钮",
  },
  {
    id: "input",
    title: "Input 输入框",
    category: "components",
    group: "数据录入",
    keywords: "input text 输入 表单",
  },
  {
    id: "checkbox",
    title: "Checkbox 多选框",
    category: "components",
    group: "数据录入",
    keywords: "checkbox check 多选 表单",
  },
];
export const toc: Record<string, [string, string][]> = {
  overview: [
    ["features", "特性"],
    ["environment", "支持环境"],
    ["progress", "当前进度"],
    ["contribute", "参与贡献"],
  ],
  start: [
    ["install", "启动文档站"],
    ["integration", "接入现有项目"],
    ["usage", "使用组件"],
    ["build", "构建与验证"],
  ],
  theme: [
    ["contract", "已验证的契约"],
    ["styling", "Tailwind CSS 与 StyleX"],
    ["limitations", "迁移边界"],
  ],
  components: [
    ["general", "通用"],
    ["entry", "数据录入"],
    ["configuration", "主题与配置"],
  ],
  "api-conventions": [
    ["state", "状态与受控输入"],
    ["refs", "ref 与原生事件"],
    ["planned", "后续 API 的边界"],
  ],
  compatibility: [
    ["matrix", "支持矩阵"],
    ["migration", "迁移检查"],
    ["pending", "待验证能力"],
  ],
  input: [
    ["when", "何时使用"],
    ["examples", "代码演示"],
    ["basic", "基本使用"],
    ["sizes", "三种大小"],
    ["controlled", "受控输入"],
    ["states", "状态"],
    ["refs", "聚焦与选择"],
    ["api", "API"],
    ["tokens", "主题变量"],
    ["limitations", "已知差异"],
  ],
  checkbox: [
    ["when", "何时使用"],
    ["examples", "代码演示"],
    ["basic", "基本使用"],
    ["states", "不可用"],
    ["controlled", "受控选择"],
    ["all", "全选与中间态"],
    ["api", "API"],
    ["tokens", "主题变量"],
    ["limitations", "已知差异"],
  ],
  button: [
    ["when", "何时使用"],
    ["examples", "代码演示"],
    ["basic", "按钮类型"],
    ["sizes", "尺寸与形状"],
    ["states", "状态与反馈"],
    ["nested", "嵌套主题"],
    ["component", "组件级覆盖"],
    ["api", "API"],
    ["limitations", "已知差异"],
  ],
};
