import type { CSSProperties } from "octane";
import { resolveButtonAlias } from "../theme/resolve";
import type { AliasToken, ButtonToken, ThemeConfig } from "../theme/types";

export function buttonVariables(
  config: ThemeConfig,
  global: AliasToken,
): CSSProperties {
  const t = resolveButtonAlias(config, global);
  const overrides = config.components?.Button;
  const contentFontSize = overrides?.contentFontSize ?? t.fontSize;
  const contentFontSizeLG = overrides?.contentFontSizeLG ?? t.fontSizeLG;
  const contentFontSizeSM = overrides?.contentFontSizeSM ?? t.fontSize;
  const c: ButtonToken = {
    fontWeight: 400,
    iconGap: t.marginXS,
    defaultShadow: `0 ${t.controlOutlineWidth}px 0 ${t.controlTmpOutline}`,
    primaryShadow: `0 ${t.controlOutlineWidth}px 0 ${t.controlOutline}`,
    dangerShadow: `0 ${t.controlOutlineWidth}px 0 ${t.colorErrorOutline}`,
    primaryColor: t.colorTextLightSolid,
    dangerColor: t.colorTextLightSolid,
    defaultColor: t.colorText,
    defaultBg: t.colorBgContainer,
    defaultBorderColor: t.colorBorder,
    defaultHoverBg: t.colorBgContainer,
    defaultHoverColor: t.colorPrimaryHover,
    defaultHoverBorderColor: t.colorPrimaryHover,
    defaultActiveBg: t.colorBgContainer,
    defaultActiveColor: t.colorPrimaryActive,
    defaultActiveBorderColor: t.colorPrimaryActive,
    borderColorDisabled: t.colorBorder,
    defaultGhostColor: t.colorBgContainer,
    defaultGhostBorderColor: t.colorBgContainer,
    ghostBg: "transparent",
    paddingInline: t.paddingContentHorizontal - t.lineWidth,
    paddingInlineLG: t.paddingContentHorizontal - t.lineWidth,
    paddingInlineSM: 8 - t.lineWidth,
    contentFontSize,
    contentFontSizeLG,
    contentFontSizeSM,
    textTextColor: t.colorText,
    textTextHoverColor: t.colorText,
    textTextActiveColor: t.colorText,
    textHoverBg: t.colorFillTertiary,
    linkHoverBg: "transparent",
    ...config.components?.Button,
  };
  const values: Record<string, string | number> = {
    height: `${t.controlHeight}px`,
    "height-sm": `${t.controlHeightSM}px`,
    "height-lg": `${t.controlHeightLG}px`,
    radius: `${t.borderRadius}px`,
    "radius-sm": `${t.borderRadiusSM}px`,
    "radius-lg": `${t.borderRadiusLG}px`,
    font: t.fontFamily,
    "font-size": `${c.contentFontSize}px`,
    "font-size-sm": `${c.contentFontSizeSM}px`,
    "font-size-lg": `${c.contentFontSizeLG}px`,
    weight: String(c.fontWeight),
    gap: `${c.iconGap}px`,
    padding: `${c.paddingInline}px`,
    "padding-sm": `${c.paddingInlineSM}px`,
    "padding-lg": `${c.paddingInlineLG}px`,
    color: c.defaultColor,
    bg: c.defaultBg,
    border: c.defaultBorderColor,
    "hover-color": c.defaultHoverColor,
    "hover-bg": c.defaultHoverBg,
    "hover-border": c.defaultHoverBorderColor,
    "active-color": c.defaultActiveColor,
    "active-bg": c.defaultActiveBg,
    "active-border": c.defaultActiveBorderColor,
    primary: t.colorPrimary,
    "primary-hover": t.colorPrimaryHover,
    "primary-active": t.colorPrimaryActive,
    "primary-color": c.primaryColor,
    error: t.colorError,
    "error-hover": t.colorErrorHover,
    "error-active": t.colorErrorActive,
    "error-bg": t.colorErrorBg,
    "error-bg-active": t.colorErrorBgActive,
    "error-border-hover": t.colorErrorBorderHover,
    "danger-color": c.dangerColor,
    link: t.colorLink,
    "link-hover": t.colorLinkHover,
    "link-active": t.colorLinkActive,
    "link-hover-bg": c.linkHoverBg,
    "text-color": c.textTextColor,
    "text-hover-color": c.textTextHoverColor,
    "text-active-color": c.textTextActiveColor,
    "text-hover-bg": c.textHoverBg,
    "text-active-bg": t.colorBgTextActive,
    "disabled-color": t.colorTextDisabled,
    "disabled-bg": t.colorBgContainerDisabled,
    "disabled-border": c.borderColorDisabled,
    "ghost-color": c.defaultGhostColor,
    "ghost-border": c.defaultGhostBorderColor,
    "ghost-bg": c.ghostBg,
    shadow: c.defaultShadow,
    "primary-shadow": c.primaryShadow,
    "danger-shadow": c.dangerShadow,
    "line-width": `${t.lineWidth}px`,
    "line-type": t.lineType,
    duration: t.motionDurationMid,
    "loading-opacity": t.opacityLoading,
    "focus-color": t.colorPrimaryBorder,
    "focus-width": `${t.lineWidthFocus}px`,
  };
  return Object.fromEntries(
    Object.entries(values).map(([key, value]) => [`--ao-btn-${key}`, value]),
  );
}
